### ISSUE TITLE
lifecycle of a LXD-Container ?

### ISSUE THREAD

**Issue by niccolox** [antitoine/lxd-functions#1]
hi

interesting script and I am trying it now

but am confused by the lifecycle

what commands to I run? when?

**Comment by antitoine** [comment]
Hi,

Thanks for your interest !
They are two commands very useful :
- `lxd-start` -> will run the container with `lxc start` and them (with `sudo`) use `bindfs` to mount the container root to map uid/gid
- `lxd-stop` -> will stop the container with `lxc stop` and them unmount it

You don't need to use other commands to use the main purpose (`lxd-bindfs-mount`, `lxd-bindfs-umount` (used in the `lxd-start/stop` commands), or even else `lxd-create` that is not properly done yet).

So if an LXD is already started, after reboot with auto-start for example, the root container will not be mounted, you need to execute `lxd-start` before work with it.
You can also mount or umount the container without start it with `lxd-bindfs-mount` and `lxd-bindfs-umount`, it's totally disconnected from the LXD lifecycle.

By default, to match uid/gid, I take the user id who executes the script in the host. In the container, if they is a user who match with the name of the container, I take his uid/gid, else it's the root user.
The method to get the user container uid/gid it's not great.
For example, I can try to find an container user properties (with `lxc config get ...`) which give the container user to make the mapping.

I'm really open to ideas and contributions. But, like you said, the main goal it's a built-in solution in LXD !

**Comment by niccolox** [comment]
Hi

How do I use it on an existing Lxd / lxc container?

How do I use it on a new container?

Do I need to stop the lxd service?

**Comment by antitoine** [comment]
Like I said, this script is totally disconnected from the LXD system, so you need to do anything.
Just update the `config.sh` file to check if the `LXD_SOURCE_DIR` match with the path of LXD containers in your system.
And set your `LXD_MOUNT_DIR` path : it's where containers will be mounted. In the example, it's `/lxd`, if you let that, you need to create a new directory named `lxd` in your root system path.

Then, just execute `lxd-start <container name>`, this will do : 
1. `lxc start ...` (if the container is already started, it's not a problem)
2. Create the `LXD_MOUNT_DIR/<container name>` directory if doesn't exist
3. Mount the container with bindfs (with `lxd-start`)

Then you can access to your container files from the host directly in the `LXD_MOUNT_DIR/<container name>` path.

You don't need to change the container and you don't need to restart the `LXD` service.

Ah, and you need to install `bindfs` in your system !

**Comment by niccolox** [comment]
> Mount the container with bindfs

how?

**Comment by niccolox** [comment]
ok, this is what I get

I created a lxd/lxc container using standard commands

```
lxd-stop dev-aegir-com
lxd-bindfs-mount dev-aegir-com devekko devekko aegir aegir
lxd-start dev-aegir-com

The user dev-aegir-com is not set in the container, therefore the default user is root.
The mount directory is not empty : /lxd/dev-aegir-com

```

when I create a test folder inside this bindfs mount I get user nobody

```
drwxrwxr-x  2 nobody nogroup  2 Jun 10 05:01 test
drwxrwxr-x  2 nobody nogroup  2 Jun 10 05:03 test2
```

**Comment by niccolox** [comment]
I should add I am using the recommended zfs image based file store, that might be causing the issue

**Comment by antitoine** [comment]
`lxd-bindfs-mount` and `lxd-bindfs-umount` is not needed, unless you want change the default mapping. 
In your example, you try to mount the container twice (first with `lxd-bindfs-mount` then with `lxd-start`) and your `lxd-bindfs-mount` command is not rigth that why you have this issue.
**Try just with `lxd-start <container name>`**, just this that (if you already have executed `lxd-bindfs-mount` before without restart your computer, execute `lxd-stop <container name>` before `lxd-start` to ensure that the container is not mounted).

I don't think the ZFS is the problem in your case. Try just with `lxd-start` and test.

If you absolutely  want to use `lxd-bindfs-mount` to use another user mapping, you need to use the uid/gid in the command parameters. Be careful with the container uid/gid, you need to get this outside the container, not inside !
**To use `lxd-bindfs-mount`, follow this example :** 

Your container name is `dev-aegir-com`, you want to match the container user/group `agir` with your host user/group `devekko`.
You need to find a file in you container `dev-aegir-com` with the right owner and the right group that will make the mapping, like `/home/aegir` with `aegir` owner and `aegir` group.
Execute in your host machine : 
- `lxd-stop dev-aegir-com`
- `ls -l /var/lib/lxd/containers/dev-aegir-com/rootfs/home/aegir` get the uid (the third column) and get the gid (the fourth column)
- `ls -l /home/devekko` get the uid (the third column) and get the gid (the fourth column)
- `lxd-bindfs-mount dev-aegir-com <devekko uid> <devekko gid> <aegir uid> <aegir gid>`

**Comment by niccolox** [comment]
this is the command I needed, I think it works, to mount a folder as a certain web app specific user

`sudo bindfs -o nonempty --force-user=1000 --force-group=1000 --create-for-user=165644 --create-for-group=165651 /var/lib/lxd/containers/dev-aegir-com/rootfs/var/aegir /lxd/dev-aegir-com/var/aegir
`

**Comment by niccolox** [comment]
THANKS FOR ALL THE HELP

**Comment by niccolox** [comment]
btw, I had to use this in host to get uid gid

```
deko@arix ~ $ egrep -i "^deko" /etc/passwd
deko:x:1000:1000:Nicholas Roberts,,,:/home/deko:/bin/bash
deko@arix ~ $ egrep -i "^deko" /etc/group
deko:x:1000:

```

**Comment by antitoine** [comment]
Great, I'm happy that it's worked for you !
And thanks for your interest !

**Comment by niccolox** [comment]
would be great if a lxd-tools repo or AWESOME LXD list collected these resources

thanks again
